variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_VERSION: 19.03.8
  #Docker version MUST match the version in the runner config.toml

image: docker:$DOCKER_VERSION

services:
  - docker:$DOCKER_VERSION-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build --network="host" -t CI_PROJECT_NAME:latest .
