name: Feature Request
description: Request a feature for REPOSITORY
title: "[Feature request]: "
labels: ["enhancement"]
assignees:
  - Griefed
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature
    attributes:
      label: Whats the feature you would like to be added?
      description: Describe the feature you would like to be added.
      placeholder: Describe, in detail, the feature you would like to be added.
      value: "Describe, in detail, the feature you would like to be added."
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else you would like to add?
      description: Any additional info you would like to add?
      placeholder: Tell me!
      value: "Tell me!"
    validations:
      required: true