name: Create Docker Dev-Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docker-dev-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: griefed
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./Dockerfile
#          build-args: BRANCH_OR_TAG=${{ github.ref_name }}
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: |
#            ghcr.io/griefed/REPOSITORY:${{ github.ref_name }}
#            ghcr.io/griefed/REPOSITORY:${{ github.ref_name }}-${{ github.sha }}
#            griefed/REPOSITORY:${{ github.ref_name }}
#            griefed/REPOSITORY:${{ github.ref_name }}-${{ github.sha }}