name: Deploy javadocs to GitHub pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      # GET LATEST CODE
      - name: Checkout latest code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

  # IF JAVA PROJECT

#      # BUILD PROJECT AND PUBLISH TO PACKAGES
#      - name: Set up JDK 8
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: '8'
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build documentation
#        run: ./gradlew about installQuasar cleanFrontend assembleFrontend copyDist build --info -x test
#      - name: List files
#        run: ls -ahl build/libs
#
#      # DEPLOY TO GH-PAGES
#      - name: Deploy to GitHub-Pages
#        uses: JamesIves/github-pages-deploy-action@4.1.5
#        with:
#          branch: gh-pages
#          folder: build/docs/javadoc

  # IF QUASAR PROJECT

#      - name: Setup Node.js environment
#        uses: actions/setup-node@v2.4.1
#        with:
#          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
#          node-version: '>= 16.1.0'
#          # Set this option if you want the action to check for the latest available version that satisfies the version spec
#          check-latest: false
#      - run: npm install -g @quasar/cli
#      - run: npm install
#      - run: quasar build
#      - run: pwd && ls -al *
#
#      # DEPLOY TO GH-PAGES
#      - name: Deploy to GitHub-Pages
#        uses: JamesIves/github-pages-deploy-action@4.1.7
#        with:
#          branch: gh-pages
#          folder: dist/spa